### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by chiliec** [8sun/yii2-integration-phpBB3.1#1]
I need instructions :baby: :baby_bottle:

**Comment by Mefistophell** [comment]
will soon be done

**Comment by TurningTide** [comment]
any updates on this?

**Comment by kenjisoul** [comment]
instructions pls

**Comment by kenjisoul** [comment]
This is instructions.
https://github.com/8sun/freestylepoker/blob/master/docs/integration.md

**Comment by Mefistophell** [comment]
https://github.com/8sun/freestylepoker/blob/master/docs/users.md
behaviors

**Comment by Mefistophell** [comment]
added instruction
