### ISSUE TITLE
Integration for Yii2 basic template

### ISSUE THREAD

**Issue by elkrari** [8sun/yii2-integration-phpBB3.1#10]
Hello,
I have a website/app based on Yii2 basic template, I tried to follow all instructions and adapt it for the  basic version, but didn't succeed.
First error I have is 

> ReflectionException
> Class nill\forum\PhpBBWebUser does not exist

Can you please help so I can complete all the needed steps to integrate the phpBB forum into my website?

**Comment by Mefistophell** [comment]
Sorry, I just now saw your message. I hope you have success.

2017-02-19 20:52 GMT+02:00 Mehdi EL KRARI <notifications@github.com>:

**Comment by elkrari** [comment]
Hello,

Not really...
Now I can see the forum but session doesn't open when I'm logged in my Yii2 application.

- I don't see the field "cookie_domain" in the table {prefix}_config to set it.

- My "username" field on the user table is "login"... I did the necessary changes except in synchronization stage: ['username' => 'username']. Both ['login' => 'username'] and ['username' => 'login'] didn't work (but which one is correct?)

**Comment by Mefistophell** [comment]
Hello! If you chose an appropriate version of phpBB you must have the field
"cookie_domain" in the table {prefix}_config in a database of a forum.

You need to give the username to PhpBBUserBahavior. In this way your User
model should to contain code like this:

public function behaviors() {
        return [
            'PhpBBUserBahavior' => [
                'class' => PhpBBUserBahavior::className(),
                'userAttr' => 'login',
                'newpassAttr' => 'password_new',
                'passAttr' => 'password',
                'emailAttr' => 'email',
            ],
        ];
    }

If you don't change cookie_domain it will not work.


2017-02-22 12:42 GMT+02:00 Mehdi EL KRARI <notifications@github.com>:

**Comment by elkrari** [comment]
I just reviewed again the table and I found the cookie_domain field, and it's set as it should to be (localhost/yii2app).
Both User and PhpBBUserBahavior classes are well defined.

I cleaned the phpBB cache and tested again but without success.

**Comment by Mefistophell** [comment]
closed due inactivity.
