### ISSUE TITLE
As I install phpbb to use this extension

### ISSUE THREAD

**Issue by tecnologiaterabyte** [8sun/yii2-integration-phpBB3.1#2]
Good afternoon, I have a doubt that is not a issue, as I install phpbb to use this extension, for example yii2-use app-advanced and want to install the forum in frontend, I install in:

Directory:

```
Views/Forum.

or

Web/Forum.
```

Or do I install it using composer I installing it in:

```
Vendor/Phpbb/phpbb
```

Thanks for your help,

Wilmer.

**Comment by Mefistophell** [comment]
Phpbb should be installed in a folder  "www\forum". Extension or through composer or unpack in "www\vendor\nill\forum\".
To work need yii2-start-application. However you can use app-advanced by making changes in the User model.
