### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by InheritX** [8sun/yii2-integration-phpBB3.1#6]
I am getting issue with one of the file is missing, thats the \forum\phpbb\di\container_builder.php

in readme its mention that : 
Part 3: Change forum settings
    "Change method get_container_filename() in \forum\phpbb\di\container_builder.php"

but there is no such file exist.

Please help me with the same.

**Comment by Mefistophell** [comment]
**\phpbb\di\container_builder.php**

Hi.
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/di/container_builder.php

As you can see in version 3.1 this file exists. Likely you are using another version.

**Comment by sergio-s** [comment]
where to look for the line  frm_config ??

> Change frm_config field cookie_domain on your domain: example - domain.loc

**Comment by Mefistophell** [comment]
> Change frm_config field cookie_domain on your domain: example - domain.loc

This is in database

**Comment by sergio-s** [comment]
Эта таблица frm_config находится в бд форума?

**Comment by Mefistophell** [comment]
Совершенно верно, в ней и нужно искать поле cookie_domain

**Comment by sergio-s** [comment]
Понял. Буду пробовать .Спасибо.
