### ISSUE TITLE
No folders  \vendor\nill\users after download extension

### ISSUE THREAD

**Issue by sergio-s** [8sun/yii2-integration-phpBB3.1#7]
I  install this extension is through composer. 
To install I followed the instructions README.md
But when I got to the line 

> ```
> Comment or delete in \vendor\nill\users\models\frontend\PasswordForm.php
> Comment or delete in \vendor\nill\users\models\frontend\Email.php
> ```
> 
> this string
> 
> use vova07\users\models\User;

I have found that in the expansion there is no such folders...

And when I run a website, an error occurs

> Class 'vova07\users\models\frontend\User' not found

Please tell me what to do and whether i can use a standard model User?
Если удобно, можно по русски.

**Comment by Mefistophell** [comment]
Спасибо за обращение.
Я действительно допустил ошибку в инструкции. Скоро исправлю и обновлю ее.

Если вы используете свою собственную модель пользователей, вам нужно всего лишь подключить к ней PhpBBUserBahavior и передать соответствующие атрибуты

```
                'class' => PhpBBUserBahavior::className(),
                'userAttr' => 'username',
                'newpassAttr' => 'password_new',
                'passAttr' => 'password',
                'emailAttr' => 'email',
```

Если вы используете расширение yii2-users-module тогда вам следует выполнить все инструкции Part 4, со следующим изменением:
Comment or delete in `\vendor\vova07\users\models\frontend\PasswordForm.php`
Comment or delete in `\vendor\vova07\users\models\frontend\Email.php`
this string
`use vova07\users\models\User;`

**Comment by sergio-s** [comment]
Спасибо. Попробую.
