### ISSUE TITLE
phpBB do not creates session

### ISSUE THREAD

**Issue by SKrav** [8sun/yii2-integration-phpBB3.1#8]
Проблема заключается в том, что при авторизации в Yii2 не создается сессия на форуме. Все функции phpBB при авторизации выдают 'SUCCESS'. Но на форуме пользователь не авторизуется, ибо не создается сессия (не сохраняется ни в куки ни в базу).  Если авторизваться через форум - сессия создается и авторизация проходит.. В чем может быть проблема и в каких направления подскажете искать?

**Comment by Mefistophell** [comment]
Проблема может быть решена при условии, что будет обязательно выполнен [пункт третий](https://github.com/8sun/yii2-integration-phpBB3.1#part-3-change-a-forum-settings) из инструкции, а так очищен кэш (лучше всего удалить все файлы в каталоге cache)

**Comment by SKrav** [comment]
Спасибо за ответ, третий пункт был выполнен. Я до конца и не понял в чем была ошибка, но в файле session.php при создании сессий создавались еще какие-то сессии ботов, и записывалась в куки сессия бота, а не текущего пользователя. Проблему режил тупо костылем: если ид текущего пользователя = ид пользователя в куках ($this->cookie_data['u']), то создать и сохранить сессию...
